name: Deploy to VPS
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      VPS_HOST: ${{vars.VPS_HOST}}
      VPS_USER: ${{vars.VPS_USER}}
      VPS_PORT: ${{vars.VPS_PORT}}
      VPS_DEPLOY_DIR: ${{vars.VPS_DEPLOY_DIR}}

    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          ssh-keyscan -H -p $VPS_PORT $VPS_HOST >> ~/.ssh/known_hosts
          cat >> ~/.ssh/config <<EOF
          Host vps
            HostName $VPS_HOST
            User $VPS_USER
            Port $VPS_PORT
            IdentityFile ~/.ssh/deploy_key
          EOF

      - name: Copy to VPS
        run: |
          rsync -az --delete ./public/ vps:$VPS_DEPLOY_ROOT